_merge = "deep"

languageCode = 'fr-fr'
title = "Conseil d'État"

[module]
[[module.imports]]
path = 'github.com/disic/frago'

[outputs]
 home    = ["HTML","JSON"]

[params]
  organisation = "Conseil d'État"
  robots = "noindex, nofollow"
